name: 'scalafmt-native-formatter'
author: 'Paweł Cembaluk <pawel.cembaluk@gmail.com>'
description: 'Uses scalafmt-native to format the code'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  conf-path:
    description: 'Path to .scalafmt.conf'
    required: false
    default: .scalafmt.conf
  args:
    description: "Scalafmt args"
    required: false
    default: "--list"
runs:
  using: "composite"
  steps:
    - run: |
        curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
        sudo bash -s -- $(${{ github.action_path }}/version.sh ${{ inputs.conf-path }}) /usr/local/bin/scalafmt-native
        echo "=============================================================================="
        echo "scalafmt-native -c ${{ inputs.conf-path }} ${{ inputs.args }}"
        scalafmt-native -c ${{ inputs.conf-path }} ${{ inputs.args }}
      shell: bash
