name: 'Simple Scalafmt'
description: 'Uses scalafmt-native to format code'
inputs:
  conf-path:
    description: 'Path to .scalafmt.conf'
    required: false
    default: .scalafmt.conf
  args:
    description: "Scalafmt args"
    required: false
    default: "--list"
runs:
  using: "composite"
  steps:
    - run: |
        curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
        sudo bash -s -- $(${{ github.action_path }}/version.sh ${{ inputs.conf-path }}) /usr/local/bin/scalafmt-native
      shell: bash
    - run: |
        echo "=============================================================================="
        echo "scalafmt-native -c ${{ inputs.conf-path }} ${{ inputs.args }}"
        scalafmt-native -c ${{ inputs.conf-path }} ${{ inputs.args }}
      shell: bash
