on: [ push ]
name: Testdata test

jobs:
  scalafmt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking testdata
        uses: ./
        with:
          conf-path: .github/testdata/.scalafmt.conf
          args: "--exclude .github/testdata/Bad.scala --list"
