on: [push, pull_request, workflow_dispatch]
name: Tests

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      formatTestWorkingDirectory: .github/tests/format-test
      versionDetectionWorkingDirectory: .github/tests/version-detection-test
    steps:
      - uses: actions/checkout@v2
      - name: Format test
        uses: ./
        with:
          conf-path: ${{ env.formatTestWorkingDirectory }}/.scalafmt.conf
          args: "--exclude ${{ env.formatTestWorkingDirectory }}/Bad.scala --list ${{ env.formatTestWorkingDirectory }}"
      - name: Version detection test
        uses: ./
        with:
          conf-path: ${{ env.versionDetectionWorkingDirectory }}/.scalafmt.conf
